/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef, useEffect } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import * as THREE from 'three'

const MapModelTRY = ({ ...props }) => {
  const group = useRef();  
  const { nodes, materials } = useLoader(GLTFLoader, '/map.gltf');
  const materialsReceivingShadow = [
    "Material_Grass_0", 
    "Material_Grass_1",
    "Material_Grass_2",
    "Material_Concrete_0",
    "Material_Concrete_1",
    "Material_Alley"
  ];
  alert("OK");
  let gh = Object.values(nodes).map((obj)=> {
    let ghj = obj.type === "Mesh" && obj.material.name;
  })
  
  return (
    <group ref={group} {...props} dispose={null}>
      {Object.values(nodes).map((obj) => 
        obj.type === "Mesh" && <mesh 
            castShadow = {materialsReceivingShadow.indexOf(obj.material.name) === -1}
            receiveShadow = {materialsReceivingShadow.indexOf(obj.material.name) !== -1}
            material = {obj.material.name}
            geometry = {obj.geometry.name}
            position = {obj.position}
            rotation = {obj.rotation}
            scale = {obj.scale}
          />
      )}
    </group>
  )}

const glassMaterial = new THREE.MeshStandardMaterial({
          color: "#7DA5A7",
    });

const MapModel = ({ ...props }) => {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/map.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-7.76, 3.76, -13.82]} rotation={[-0.26, -0.95, 0.62]} scale={[0.29, 0.29, 0.29]}>
        <mesh castShadow material={materials.Material_Leaves_0} geometry={nodes.Icosphere012.geometry} />
        <mesh castShadow material={materials.Material_Leaves_Dark_0} geometry={nodes.Icosphere012_1.geometry} />
        <mesh castShadow material={materials.Material_Wood} geometry={nodes.Icosphere012_2.geometry} />
      </group>
      <mesh
      castShadow 
        material={materials.Material_Leaves_0}
        geometry={nodes.Icosphere008.geometry}
        position={[-5.45, 0.09, -12.32]}
        rotation={[-0.61, 0.39, 0.91]}
        scale={[0.36, 0.36, 0.36]}
      />
      <mesh
        castShadow 
        material={materials.Material_Leaves_1}
        geometry={nodes.Icosphere007.geometry}
        position={[-5.45, 0.24, -12.32]}
        rotation={[-0.61, 0.39, 0.91]}
        scale={[0.36, 0.36, 0.36]}
      />
      <group position={[-9.92, 3.64, -4.69]} rotation={[-0.16, 0.4, 0.9]} scale={[0.37, 0.37, 0.37]}>
        <mesh castShadow material={materials.Material_Leaves_0} geometry={nodes.Icosphere009.geometry} />
        <mesh castShadow material={materials.Material_Leaves_Dark_0} geometry={nodes.Icosphere009_1.geometry} />
        <mesh castShadow material={materials.Material_Wood} geometry={nodes.Icosphere009_2.geometry} />
      </group>
      <group position={[-2.43, 5.32, -15.1]} rotation={[-2.99, -0.23, -2.27]} scale={[0.37, 0.37, 0.37]}>
        <mesh castShadow material={materials.Material_Wood} geometry={nodes.Icosphere002_1.geometry} />
        <mesh castShadow material={materials.Material_Leaves_Dark_1} geometry={nodes.Icosphere002_2.geometry} />
        <mesh castShadow material={materials.Material_Leaves_1} geometry={nodes.Icosphere002_3.geometry} />
      </group>
      <mesh castShadow material={materials.Material_Wood} geometry={nodes.Ground001.geometry} />
      <mesh castShadow 
        material={materials.Material_Leaves_0}
        geometry={nodes.Icosphere006.geometry}
        position={[-1.81, 0.09, 8.55]}
        rotation={[-1.92, 0.63, 2.73]}
        scale={[0.36, 0.36, 0.36]}
      />
      <mesh castShadow 
        material={materials.Material_Leaves_1}
        geometry={nodes.Icosphere005.geometry}
        position={[14.58, 0.24, 2.36]}
        rotation={[-1.97, -0.95, -1.4]}
        scale={[0.36, 0.36, 0.36]}
      />
      <mesh
        material={materials.Material_Leaves_0}
        geometry={nodes.Icosphere004.geometry}
        position={[14.58, 0.09, 2.36]}
        rotation={[-1.97, -0.95, -1.4]}
        scale={[0.36, 0.36, 0.36]}
      />
      <mesh castShadow 
        material={materials.Material_Leaves_1}
        geometry={nodes.Icosphere002.geometry}
        position={[0.05, 0.09, 12.61]}
        rotation={[-1.92, 0.63, 2.73]}
        scale={[0.36, 0.36, 0.36]}
      />
      <mesh castShadow 
        material={materials.Material_Leaves_0}
        geometry={nodes.Icosphere003.geometry}
        position={[14.43, -0.17, 15.52]}
        rotation={[-1.7, -1.27, -2.26]}
        scale={[0.87, 0.87, 0.87]}
      />
      <mesh castShadow 
        material={materials.Material_Leaves_0}
        geometry={nodes.Icosphere001.geometry}
        position={[15.68, -0.24, 14.39]}
        rotation={[-1.7, -1.27, -2.26]}
        scale={[0.65, 0.65, 0.65]}
      />
      <mesh castShadow 
        material={materials.Material_Leaves_0}
        geometry={nodes.Icosphere.geometry}
        position={[12.2, -0.24, 15.93]}
        rotation={[-0.51, -0.32, 0.62]}
        scale={[0.65, 0.65, 0.65]}
      />
      <mesh castShadow 
        material={materials.Material_Leaves_0}
        geometry={nodes.Icosphere000.geometry}
        position={[11.42, 0.09, 15.9]}
        rotation={[-2.25, 0.2, -2.78]}
        scale={[0.36, 0.36, 0.36]}
      />
      <mesh receiveShadow material={materials.Material_Grass_1} geometry={nodes.Mesh001.geometry} />
      <mesh receiveShadow material={materials.Material_Concrete_0} geometry={nodes.Mesh001_1.geometry} />
      <mesh receiveShadow material={materials.Material_Sand_0} geometry={nodes.Mesh001_2.geometry} />
      <mesh receiveShadow material={materials.Material_Sand_1} geometry={nodes.Mesh001_3.geometry} />
      <mesh receiveShadow material={materials.Material_Alley} geometry={nodes.Mesh001_4.geometry} />
      <mesh receiveShadow material={materials.Material_Grass_0} geometry={nodes.Mesh001_5.geometry} />
      <mesh receiveShadow material={materials.Material_Grass_2} geometry={nodes.Mesh001_6.geometry} />
      <group position={[-10.53, 0.79, 12.72]} rotation={[-Math.PI, 0, -Math.PI]} scale={[3.56, 1.37, 2.01]}>
        <mesh castShadow material={materials.Material_Wall_3} geometry={nodes.Cube004_1.geometry} />
        <mesh castShadow material={materials.Material_White} geometry={nodes.Cube004_2.geometry} />
        <mesh castShadow material={materials.Material_Wall_4} geometry={nodes.Cube004_3.geometry} />
        <mesh castShadow material={materials.Material_Wall_Concrete} geometry={nodes.Cube004_4.geometry} />
        <mesh castShadow material={glassMaterial} geometry={nodes.Cube004_5.geometry} />
        <mesh castShadow material={materials.Material_Wall_0} geometry={nodes.Cube004_6.geometry} />
      </group>
      <group position={[-12.73, 0, 0.61]} rotation={[0, Math.PI / 2, 0]} scale={[3.09, 1.18, 2.8]}>
        <mesh castShadow material={materials.Material_Wall_1} geometry={nodes.Cube003_1.geometry} />
        <mesh castShadow material={glassMaterial} geometry={nodes.Cube003_2.geometry} />
        <mesh castShadow material={materials.Material_White} geometry={nodes.Cube003_3.geometry} />
      </group>
      <group position={[-8.02, 1.07, -10.83]} rotation={[-Math.PI, -1.57, 0]} scale={[-0.88, -0.88, -0.88]}>
        <mesh castShadow material={glassMaterial} geometry={nodes.Cube001_1.geometry} />
        <mesh castShadow material={materials.Material_Concrete_1} geometry={nodes.Cube001_2.geometry} />
        <mesh castShadow material={materials.Material_White} geometry={nodes.Cube001_3.geometry} />
        <mesh castShadow material={materials.Material_Concrete_0} geometry={nodes.Cube001_4.geometry} />
        <mesh castShadow material={materials.Material_Wall_Concrete} geometry={nodes.Cube001_5.geometry} />
        <mesh castShadow material={materials['Material_ Beige']} geometry={nodes.Cube001_6.geometry} />
        <mesh castShadow material={materials.Material_Wall_0} geometry={nodes.Cube001_7.geometry} />
      </group>
      <group position={[0.18, 3.76, -13.15]} rotation={[-0.26, -0.95, 0.62]} scale={[0.29, 0.29, 0.29]}>
        <mesh castShadow material={materials.Material_Leaves_0} geometry={nodes.Icosphere014.geometry} />
        <mesh castShadow material={materials.Material_Leaves_Dark_0} geometry={nodes.Icosphere014_1.geometry} />
        <mesh castShadow material={materials.Material_Wood} geometry={nodes.Icosphere014_2.geometry} />
      </group>
      <group position={[-5.86, 0.55, -5.27]} rotation={[-2.46, 0.41, -2.48]} scale={[0.53, 0.53, 0.53]}>
        <mesh castShadow material={materials['Material_Wood.001']} geometry={nodes.Icosphere008_1.geometry} />
        <mesh castShadow material={materials.Material_Leaves_2} geometry={nodes.Icosphere008_2.geometry} />
        <mesh castShadow material={materials.Material_Leaves_3} geometry={nodes.Icosphere008_3.geometry} />
      </group>
    </group>
  )
}

export const Map = ({ ...props }) => {

  return (
    <group>
      <group position={[0,-0.25,0]} scale={[1,1,1]}>
        <MapModel />
      </group>
    </group>
  )
}
