/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef, useEffect } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export const Map = ({ ...props }) => {
  const { scene } = useLoader(GLTFLoader, '/map.gltf');
  const ref = useRef();

  return (
    <group ref={ref}>
      <group scale={[4,4,4]}>
        <primitive object={scene}  />
      </group>
    </group>
  )
}
