/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef, useEffect } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export const Pines = () => {
  const gltf = useLoader(GLTFLoader, '/pines.gltf');
  const ref = useRef();

  return (
    <group>
      <group position={[0,-1.25,0]} scale={[1,1,1]}>
        <mesh receiveShadow castShadow ref={ref}>
            <primitive object={gltf.scene} dispose={null} />
        </mesh>
      </group>
    </group>
  )
}
