/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef, useEffect } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export const World = ({ ...props }) => {
  const { nodes, materials } = useLoader(GLTFLoader, '/map.gltf');
  const ref = useRef();

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        position={[0, -0.25, 0]}
        material={materials.Ground}
        geometry={nodes.Ground.geometry}
        scale={[1, 1, 1]}
      />
    </group>
  )
}
/*
const gltf = useLoader(GLTFLoader, '/map.gltf');
  const ref = useRef();

  return (
    <group ref={ref}>
      <group position={[0,-0.25,0]} scale={[1,1,1]}>
        <mesh>
            <bufferGeometry attach="geometry" {...gltf.__$[10].geometry} />
            <meshStandardMaterial attach="material" {...gltf.__$[10].material} 
            color={props.castShadow? "red" : "blue"}/>
        </mesh>
      </group>
    </group>
  )*/